### ISSUE TITLE
Auto-sorting on save

### ISSUE THREAD

**Issue by stanislavshabalin** [hudochenkov/sublime-postcss-sorting#1]
Is it possible to automatically sort CSS rules (on every file save, for example)?

**Comment by hudochenkov** [comment]
It's possible to do on file save.

**Comment by stanislavshabalin** [comment]
I can try to implement that, if you don't mind.
Do you have any tips or comments up front?

I guess it should be an option disabled by default.

**Comment by hudochenkov** [comment]
In sublime-autoprefixer this [function was added recently](https://github.com/sindresorhus/sublime-autoprefixer/commit/2df8ab85dd8ed94ec3955ba8fe09508182f2e443). You can copy almost whole commit :) But read discussion on [this PR](https://github.com/sindresorhus/sublime-autoprefixer/pull/65) (with comments for outdated diffs) first. And remember that my plugin support not only CSS syntax, but PostCSS and SCSS also.

Yes, it should be disabled by default.

**Comment by stanislavshabalin** [comment]
@hudochenkov Is it a feature that plugin attempts to sort unknown syntax when run manually?
![sublime-postcss-sorting](https://cloud.githubusercontent.com/assets/420771/12204140/376156f6-b654-11e5-9f85-4d2e82c8ae3a.png)

I can see that it is, since there might be some unexpected syntax like `JavaScript (Babel)`, only for CSS :-)  

Upd: or they could be editing `.pcss` file without syntax plugin so it would appear as `Plain Text`.

**Comment by hudochenkov** [comment]
There is not syntax check because we assume that developer know why PostCSS Sorting should process that file.
