### ISSUE TITLE
Not working with sass

### ISSUE THREAD

**Issue by ghost** [hudochenkov/sublime-postcss-sorting#12]
Hi,

I can not make it work with sass. With css it works very well.

```
Error: 3:13: Missed semicolon
```

I think it's because postcss only expects css by default?

I also install @csstools/postcss-sass but I do not know how to integrate it into postcss with sublime. Can you help me?

**Comment by hudochenkov** [comment]
This plugin works only with CSS, SCSS, and PostCSS.

**Comment by ghost** [comment]
Ok sad
