### ISSUE TITLE
Common Config for both stylelint-order and this plugin

### ISSUE THREAD

**Issue by rgant** [hudochenkov/sublime-postcss-sorting#13]
I'm switching over to stylelint, using stylelint-order and this sublime text package. Right now I have two copies of my configuration to sort properties: One in the `.sublime-project` file and another in `.stylelintrc.yml` is there a way to use only one configuration?

For example, it would be nice if this plugin could look for the stylelint [configuration files](https://stylelint.io/user-guide/configuration#loading-the-configuration-object) and use those to determine the sorting.

**Comment by hudochenkov** [comment]
You can use [`stylelint-order`](https://github.com/hudochenkov/stylelint-order) with stylelint instead of this plugin. I'm afraid Sublime Text plugin won't be developed anymore, because I no longer use Sublime Text.

**Comment by rgant** [comment]
Would you be open to transferring this project to someone else then? Maybe update the README to indicate that it's unmaintained?

**Comment by hudochenkov** [comment]
If someone is willing to support it, I'm open for this. PRs are welcome.
