### ISSUE TITLE
Nothing happens after "Run PostCSS sorting" or stylelint error

### ISSUE THREAD

**Issue by hirschferkel** [hudochenkov/sublime-postcss-sorting#14]
On one machine with OS X running PostCSS Sublime will only mark the document to be "changed" but actually nothing happens. There is even no message in console, too. Does anyone know what I can do?

On the second machine I will just get the following error message:
```
SublimeLinter: WARNING: stylelint output:
Error: No configuration provided for [name and path of current file]
    at module.exports (/usr/local/lib/node_modules/stylelint/lib/utils/configurationError.js:10:14)
    at /usr/local/lib/node_modules/stylelint/lib/getConfigForFile.js:56:11
```
Any idea what can be done?
Best, hirschferkel

**Comment by hudochenkov** [comment]
This plugin has nothing to do with stylelint.

**Comment by hirschferkel** [comment]
O.k. but it doesn't work so maybe this has something to do with the plugin? How can I get it work. It states "Changed" but nothing happens?
