### ISSUE TITLE
Can't find Node

### ISSUE THREAD

**Issue by lannex** [hudochenkov/sublime-postcss-sorting#6]
I'm using nvm.
So it probably seems that there is no node in '/ usr / local / bin'.

Thank you anyway!

**Comment by hudochenkov** [comment]
Sorry I don't know anything about nvm. You can try to create a symlink to `/usr/local/bin`

Read more:
https://github.com/creationix/nvm/issues/786
http://stackoverflow.com/questions/38485647/how-to-use-node-in-usr-local-bin-instead-of-the-one-in-nvm
