### ISSUE TITLE
postcss-sorting recently stopped working

### ISSUE THREAD

**Issue by Alecto** [hudochenkov/sublime-postcss-sorting#7]
i use latest sublime text 3 version.
node.js v6.9.5
I do not know why and when it happened, but postcss-sorting stopped working recently, maybe 1-2 weeks ago.
node.js working, i test cmd.
no errors from postcss-sorting in sublime text console.
it doesnt work on save and if i choose command in menu.
help me plz.

http://image.prntscr.com/image/5b3c3a32de8e4cdcbeb57e4b3980da8a.png

**Comment by hudochenkov** [comment]
What plugin version do you use? Plugin uses `postcss-sorting@2.0.0` for a month now, which have different config than previous version. This is probably why it's not working for you. You should have received a message from Package Control about this, when it have updated this plugin. Take a look at [migration guide](https://github.com/hudochenkov/postcss-sorting#migration-from-1x).

**Comment by Alecto** [comment]
2.0.1
i reinstalled it - doesnt work
http://image.prntscr.com/image/55c9857b2fdd4ad09761958d6faab02f.png

**Comment by Alecto** [comment]
i delete old postscss-sorting and re-installed it.
then i check node.js
http://image.prntscr.com/image/c2c46793f5b241ab8495883f354a68e1.png
I still have to manually migrate configuration?

**Comment by hudochenkov** [comment]
You should update your config for a new version. See my previous comment for a migration guide.

Yes, you have to manually migrate configuration.

**Comment by Alecto** [comment]
I read 10 times, but did not understand what to do with files, which change them.
i download file from "PostCSS Sorting predefined configs migrated to 2.0"
search in sublime found and replaced the same files.
http://image.prntscr.com/image/d96b0ce1b4054936b4f142e988726e52.png
then I restart the program, but the sorting is not working.
probably something I'm doing wrong, but I can not figure out what it was.

**Comment by hudochenkov** [comment]
You should update settings which you can find in Sublime Text: Preferences → Package Settings → PostCSS Sorting → Settings - User. What do you have there now?

**Comment by Alecto** [comment]
it was like this
http://image.prntscr.com/image/e26cbc4b29664039925e467451b281a0.png
I replaced sort-order to order
http://image.prntscr.com/image/c66a026838c24d34a3448e3e01d27aa0.png

**Comment by Alecto** [comment]
i have all from default.json insert into settings--user?

**Comment by Alecto** [comment]
look like sorting works now! thank U!!!!!
Another question: sorting while maintaining the works, but blank lines between child rules are added.
No error messages.
here, too, something changed?

http://image.prntscr.com/image/564960ca6a3348259520998dd39eff3d.png

**Comment by hudochenkov** [comment]
The new version doesn't add or remove any empty lines by default. Please read what options were removed and added in the new version: https://github.com/hudochenkov/postcss-sorting/blob/master/CHANGELOG.md#200 And configure plugin with your liking. If you're using stylelint, you may find that option for empty lines very similar to stylelint's rules.

**Comment by Alecto** [comment]
now i use
```
{

"rule-nested-empty-line-before": true,

"sort-on-save": true,


    "order": [
        "custom-properties",
...

```
its work for me!!!
like understood, once again - thank you very much for your help!

**Comment by hudochenkov** [comment]
You're welcome! Feel free to ask if you have more questions.
