### ISSUE TITLE
sublime-postcss-sorting doesn't do anything on my OSx El Capitan

### ISSUE THREAD

**Issue by avmax** [hudochenkov/sublime-postcss-sorting#8]
Hello! I used to use your wonderful plugin in my sublime text, which was installed on Linux. And it worked fine. Recently I moved to mac, OSx El captain. And it doesn't work here! I've checked if node is in /usr/local/bin - exe of node is there. Postcss sorting doesn't show any mistakes in sublime. Can you give me some advice, please?

**Comment by hudochenkov** [comment]
I'm using it on macOS.

Did you notice `postcss-sorting` was updated to `v2.0` recently and config changed? Maybe this is the reason. Check the [changelog](https://github.com/hudochenkov/postcss-sorting/releases/tag/2.0.0) and [migration guide](https://github.com/hudochenkov/postcss-sorting#migration-from-1x).

**Comment by avmax** [comment]
oh. thanks. well, I've mentioned now that by default this plugin does nothing.

1) As I understood https://gist.github.com/hudochenkov/b7127590d3013a5982ed90ad63a85306#file-default-json-L1-L233 - the part I selected is a new example of default config for sublime - am I right?

2) And where can I find special commands, such as "sort-on-save" ? 

3) For such settings as "at-rule-nested-empty-line-before" - is it possible to set up several lines, not just one? as in old version

**Comment by hudochenkov** [comment]
1. You're right.
2. There is only one special Sublime Text option: `sort-on-save`. Copy config from the link you've found, and add new property to it.
3. No, it's not possible.

**Comment by avmax** [comment]
@hudochenkov thanks
