### ISSUE TITLE
Sorting doesnt work on save

### ISSUE THREAD

**Issue by Alecto** [hudochenkov/sublime-postcss-sorting#9]
Hi.
I have one more problem.
There are two notebooks, which has the same version ST3 with the same set of plug-ins and with the same settings (copy from one to another).
One notebook sorting works when i save file, the second - is not, only the direct call of the sort menu (or ctrl+ alt+ shift + s).

```
{

    "sort-on-save": true,
    
    "rule-nested-empty-line-before": [
      "always-multi-line",
      {
        "except": ["first-nested"],
        "ignore": ["after-comment"]
      }
    ],


    "order": [
        "custom-properties",
        "dollar-variables",
        "at-rules",
        "declarations",
        {
            "type": "at-rule",
            "name": "media"
        },
        "rules"
    ],
    "properties-order": [
        "lost-utility",
......................... 
        "stroke"
    ],
    "unspecified-properties-position": "bottom"
}

```

the settings is equal, no errors on the second notebook, when saving.
can U help me plz?

**Comment by Alecto** [comment]
"sort-on-save": true - Stopped working on the second computer.

my config:

{

    "rule-nested-empty-line-before": [
      "always-multi-line",
      {
        "except": ["first-nested"],
        "ignore": ["after-comment"]
      }
    ],
    "order": [
        "custom-properties",
        "dollar-variables",
        "at-rules",
        "declarations",
        {
            "type": "at-rule",
            "name": "media"
        },
        "rules"
    ],
    "properties-order": [
        "lost-utility",
.......................................................
        "stroke"
    ],
    "unspecified-properties-position": "bottom",
    "sort-on-save": true
}


ctrl+ alt+ shift + s - sorting

**Comment by Alecto** [comment]
It seems that the problem is in the plugin "Sass", that I replaced the "SCSS".
when the page higlighted as SCSS - sort-on-save works, when Sass or Less - dont work (but ctrl+ alt+ shift + s - still works)

**Comment by hudochenkov** [comment]
Sorry for a delay. Auto-sorting on save works only for 'CSS', 'PostCSS', and 'SCSS' syntaxes.

**Comment by Alecto** [comment]
Has already established by experience.
Thanks for the answer, I'll know.
